"""empty message

Revision ID: 08363b9e429c
Revises: 731a834f9072
Create Date: 2023-09-27 10:54:39.420269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08363b9e429c'
down_revision = '731a834f9072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('disc', sa.String(length=1000), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('disc')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
