"""empty message

Revision ID: 22a46247e1ad
Revises: 08363b9e429c
Create Date: 2023-09-27 11:16:13.158485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22a46247e1ad'
down_revision = '08363b9e429c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('disc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disc', mysql.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
