"""empty message

Revision ID: 4fe45e32531d
Revises: 3024228d38b5
Create Date: 2023-10-05 19:29:51.375719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe45e32531d'
down_revision = '3024228d38b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('cart_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_ibfk_1', 'book', ['author'], ['id'])

    # ### end Alembic commands ###
