"""empty message

Revision ID: 997866cd5540
Revises: 9dbbd5889a4c
Create Date: 2023-09-24 09:45:11.270055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997866cd5540'
down_revision = '9dbbd5889a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('logo_name')

    # ### end Alembic commands ###
