"""empty message

Revision ID: 9dbbd5889a4c
Revises: c024f98c0014
Create Date: 2023-09-24 09:27:37.299895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbbd5889a4c'
down_revision = 'c024f98c0014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DateOFbirth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('DateOFbirth')

    # ### end Alembic commands ###
