"""empty message

Revision ID: a73745aae90e
Revises: d9544c93c78c
Create Date: 2023-12-10 09:26:23.384869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73745aae90e'
down_revision = 'd9544c93c78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('order_ibfk_1', 'user', ['seller_id'], ['id'])

    # ### end Alembic commands ###
