"""empty message

Revision ID: b260e124e497
Revises: 
Create Date: 2023-11-24 08:23:11.293026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b260e124e497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['seller_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_ibfk_1', 'user', ['author'], ['id'])
        batch_op.drop_column('seller_id')
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###
