"""empty message

Revision ID: c024f98c0014
Revises: 64c5cd9ede97
Create Date: 2023-09-16 10:50:08.240754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c024f98c0014'
down_revision = '64c5cd9ede97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint('post_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_ibfk_1', 'user', ['author'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('author',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
