"""empty message

Revision ID: d9544c93c78c
Revises: b056b19f63b8
Create Date: 2023-12-10 08:44:28.869724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9544c93c78c'
down_revision = 'b056b19f63b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_adress', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('buyer_adress')

    # ### end Alembic commands ###
